export interface Book {
    id: number,
    title: string,
    sutitle?: string | null,
    author?: string | null,
    publisher?: string | null,
    isbn?: string | null,
    description?: string | null,
    language?: string | null,
    year: number,
    pages: number,
    price: number,
    stock: number,
    discount:number,
    available: boolean,
    dimensions?: string | null,
    width: number,
    cover?: string | null,
    cover_url?: string | null,
}
